#!/usr/bin/env python

# Referenced from modules/tinyexr/SCsub

Import("env")
Import("env_modules")

env_ruby = env_modules.Clone()

thirdparty_obj = []

thirdparty_dir = "#thirdparty/mruby/"
thirdparty_sources = [

]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_ruby.Prepend(CPPPATH=[thirdparty_dir])

env.Append(LIBPATH=[thirdparty_dir + "lib"])
env.Append(LINKFLAGS=["libmruby.lib", "libmruby_core.lib"])

env_thirdparty = env_ruby.Clone()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []

env_ruby.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

env.Depends(module_obj, thirdparty_obj)
